apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-exercise
  #namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-exercise
  template:
    metadata:
      labels:
        app: devops-exercise
    spec:
      containers:
      - name: devops-exercise
        image: joselebasi/repositoryone:068cddf7b08dada1aa5c4ddbde49045decaf6cd7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAME_DEV
          valueFrom:
            configMapKeyRef:
              name: app-python-cfm
              key: name_dev