apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-exercise
  #namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-exercise
  template:
    metadata:
      labels:
        app: devops-exercise
    spec:
      containers:
      - name: devops-exercise
        image: joselebasi/repositoryone:d9d6919afc5a58bab16318e23c905d1fa0f11a87
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: host
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: password
        - name: REDIS_PORT
          value: "6379"
        - name: NAME_DEV
          valueFrom:
            configMapKeyRef:
              name: app-python-cfm
              key: name_dev