apiVersion: v1
kind: Service
metadata:
  name: devops-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: devops-exercise
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000

