apiVersion: v1
kind: Service
metadata:
  name: devops-service
  #namespace: devops
spec:
  type: NodePort
  selector:
    app: devops-exercise
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000

