apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        command: ["redis-server"]
        args: ["--save 60 1", "--loglevel warning"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redisvolume
          mountPath: /data
      volumes:
      - name: redisvolume
        
