apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
type: Opaque
data:
  host: cmVkaXMK
  password: YS12ZXJ5LWNvbXBsZXgtcGFzc3dvcmQtaGVyZQo=

# Esto se puede crear a mano:
# kubectl create secret generic db-credentials --from-literal=username=admin --from-literal=password=sup3rpassw0rd
# Docs: https://kubernetes.io/es/docs/concepts/configuration/secret/