apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  #Azure
  storageClassName: managed-csi
  
  #Digital Ocean
  #storageClassName: do-block-storage
